# Generated by Django 5.0.6 on 2024-07-15 05:29

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_membership_customuser_joined_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.PathAndRename('profiles/')),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_picture',
            field=models.ImageField(blank=True, null=True, upload_to='team_pictures/'),
        ),
    ]
