# Generated by Django 5.0.6 on 2024-07-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_updated_at_alter_player_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='media/profiles/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/team_pictures/'),
        ),
    ]
