# Generated by Django 5.0.6 on 2024-07-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
