# Generated by Django 5.0.6 on 2024-07-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscriptionplan_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
