# Generated by Django 5.0.6 on 2024-07-15 02:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='description',
            new_name='team_description',
        ),
        migrations.RemoveField(
            model_name='club',
            name='founded',
        ),
        migrations.RemoveField(
            model_name='club',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='club',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='club',
            name='name',
        ),
        migrations.RemoveField(
            model_name='club',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='club',
            name='stadium',
        ),
        migrations.AddField(
            model_name='club',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='club',
            name='team_club_picture',
            field=models.ImageField(blank=True, null=True, upload_to='team_club_pictures/'),
        ),
        migrations.AddField(
            model_name='club',
            name='team_name',
            field=models.CharField(default='default_team_name', max_length=255),
        ),
        migrations.AddField(
            model_name='club',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
