# Generated by Django 5.0.6 on 2024-07-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
