# Generated by Django 5.0.6 on 2024-07-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_teaminfo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminfo',
            name='slug',
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='team_name_search',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
