# Generated by Django 5.0.6 on 2024-07-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_rename_description_club_team_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
