# Generated by Django 5.0.6 on 2024-07-29 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('info', '0003_remove_teaminfo_slug_teaminfo_team_name_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name_search', models.CharField(blank=True, max_length=255, unique=True)),
                ('biography', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='player_pictures/')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_info', to='accounts.player')),
            ],
        ),
    ]
