# Generated by Django 5.0.6 on 2024-07-15 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_membership_customuser_joined_teams'),
        ('info', '0003_alter_club_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='default_team_name', max_length=255)),
                ('team_club_picture', models.ImageField(blank=True, null=True, upload_to='team_club_pictures/')),
                ('team_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_info', to='accounts.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Club',
        ),
    ]
