# Generated by Django 5.0.6 on 2024-07-29 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_playerinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaminfo',
            old_name='team_name_search',
            new_name='info_team_name',
        ),
        migrations.RemoveField(
            model_name='teaminfo',
            name='team_description',
        ),
        migrations.RemoveField(
            model_name='teaminfo',
            name='team_name',
        ),
        migrations.DeleteModel(
            name='PlayerInfo',
        ),
    ]
