# Generated by Django 5.0.6 on 2024-07-29 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('info', '0007_remove_communitymembership_community_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_player_name', models.CharField(blank=True, max_length=100, unique=True)),
                ('player_picture', models.ImageField(blank=True, null=True, upload_to='player_pictures/')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='accounts.player')),
            ],
        ),
    ]
